# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate Fonts (Testing)

on:
  push:
    tags:
      - "testing-*"

jobs:
  build:
    runs-on: ubuntu-latest
    continue-on-error: true
    env:
      TEST_RUN: true

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - run: sudo apt install wget
      - name: Set up Python 3.9.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.9.x
      - uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.1

      - name: Cache Poetry virtualenv
        uses: actions/cache@v1
        id: cache
        with:
          path: ~/.virtualenvs
          key: poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: |
            poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Set Poetry config
        run: |
          poetry config virtualenvs.in-project false
          poetry config virtualenvs.path ~/.virtualenvs

      - name: Install Dependencies
        run: poetry install
        if: steps.cache.outputs.cache-hit != 'true'

      - run: sh fetch_dump.sh
      - run: sh fetch_svg_font.sh

      - run: gzip -d *.txt.gz
      - run: sh clean.sh || exit 0
      - name: Mincho SC
        run: |
          CONFIG=./config_mincho_single.json poetry run driver ./glyphwiki_dump/dump_newest_only.txt ./glyphwiki_mincho.txt ./perl-scripts g
          shopt -s extglob
          zip HanaMinLiteSC.zip {Hana*.!(otf),GlyphWiki*}
          rm {Hana*.!(otf),GlyphWiki*}

      - run: sh clean.sh || exit 0
      - name: Mincho TC CJK
        run: |
          CONFIG=./config_mincho.json poetry run driver ./glyphwiki_dump/dump_newest_only.txt ./glyphwiki_mincho.txt ./perl-scripts t
          shopt -s extglob
          zip HanaMinLiteCJKTC.zip {Hana*.!(otf),GlyphWiki*}
          rm {Hana*.!(otf),GlyphWiki*}

      - run: sh clean.sh || exit 0
      - name: Gothic JP
        run: |
          CONFIG=./config_gothic_single.json poetry run driver ./glyphwiki_dump/dump_newest_only.txt ./glyphwiki_gothic.txt ./perl-scripts j
          shopt -s extglob
          zip HanaGothLiteJP.zip {Hana*.!(otf),GlyphWiki*}
          rm {Hana*.!(otf),GlyphWiki*}

      - run: sh clean.sh || exit 0
      - name: Gothic KR CJK
        run: |
          CONFIG=./config_gothic.json poetry run driver ./glyphwiki_dump/dump_newest_only.txt ./glyphwiki_mincho.txt ./perl-scripts t
          shopt -s extglob
          zip HanaGothLiteCJKKR.zip {Hana*.!(otf),GlyphWiki*}
          rm {Hana*.!(otf),GlyphWiki*}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            *.otf
            *.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
